import './style.scss';
import { ILevel } from '../../types/types';

export const levels: ILevel[] = [
  {
    levelNumber: 1,
    levelTitle: 'Сhoose white cubes',
    items: ['cube', 'cube'],
    classes: [null, 'cube'],
    answer: 'cube',
    markup: ['<cube />', '<cube />'],
  },
  {
    levelNumber: 2,
    levelTitle: 'Сhoose red balls',
    items: ['ball', 'little-ball', 'ball'],
    classes: [null, null, null],
    answer: 'ball',
    markup: ['<ball />', '<little-ball />', '<ball />'],
  },
  {
    levelNumber: 3,
    levelTitle: 'Сhoose red balls',
    items: ['little-cube', 'cube', 'ball'],
    classes: [null, null, null],
    answer: 'ball',
    markup: ['<little-cube />', '<cube />', '<ball />'],
  },
  {
    levelNumber: 4,
    levelTitle: 'Сhoose white cubes',
    items: ['ball', 'cube', 'cube'],
    classes: [null, null, null],
    answer: 'cube',
    markup: ['<ball />', '<cube />', '<cube />'],
  },
  {
    levelNumber: 5,
    levelTitle: 'Сhoose white cubes',
    items: ['ball', 'cube', 'cube', 'ball','ball'],
    classes: [null, null, null, null, null],
    answer: 'cube',
    markup: ['<ball />', '<cube />', '<cube />', '<ball />','<ball />'],
  },
  {
    levelNumber: 6,
    levelTitle: 'Сhoose pyramid',
    items: ['cube', 'pyramid', 'little-cube', 'pyramid','ball'],
    classes: [null, null, null, null],
    answer: 'pyramid',
    markup: ['<cube />', '<pyramid />', '<little-cube />', '<pyramid />','<ball />'],
  },
  {
    levelNumber: 7,
    levelTitle: 'Сhoose pyramid',
    items: ['pyramid', 'little-ball', 'pyramid', 'little-cube','ball'],
    classes: [null, null, null, null, null],
    answer: 'pyramid',
    markup: ['<pyramid />', '<little-ball />', '<pyramid />', '<little-cube />','<ball />'],
  },
  {
    levelNumber: 8,
    levelTitle: 'Сhoose pyramid',
    items: ['pyramid', 'little-cube', 'little-ball', 'pyramid','ball'],
    classes: [null, null, null, null, null],
    answer: 'pyramid',
    markup: ['<pyramid />', '<little-cube />', '<little-ball />', '<pyramid />','<ball />'],
  },
  {
    levelNumber: 9,
    levelTitle: 'Сhoose pyramid',
    items: ['little-ball', 'pyramid', 'ball', 'pyramid','little-cube'],
    classes: [null, null, null, null, null],
    answer: 'pyramid',
    markup: ['<little-ball />', '<pyramid />', '<ball />', '<pyramid />','<little-cube />'],
  },
  {
    levelNumber: 10,
    levelTitle: 'Сhoose pyramid',
    items: ['pyramid', 'little-ball', 'pyramid', 'little-cube','ball'],
    classes: [null, null, null, null, null],
    answer: 'pyramid',
    markup: ['<pyramid />', '<little-ball />', '<pyramid />', '<little-cube />','<ball />'],
  }
]
